### ISSUE TITLE
Calamari not dropping

### ISSUE THREAD

**Issue by Kryneth** [PhantomWing/RusticDelight#15]
(I am using Fabric for 1.21.1 of Minecraft. The mod version is 1.0.1.)

 I can't seem to get calamari to drop from squids or glow squids, no matter what I kill them with. None of the other mods I have should affect squids or glow squids at all. The only mod that I have (other than Farmer's Delight of course) that affects drops on vanilla mobs is Knightquest, but squids are unchanged.

**Comment by PhantomWing** [comment]
Thanks for reporting this, the fix is now available to download! Squids should drop Calamari whenever they are killed, doesn't matter which tool :)
