### ISSUE TITLE
Cannot cut cherry blossom cheesecake pie into slices with cutting board 

### ISSUE THREAD

**Issue by thelegitdolt** [PhantomWing/RusticDelight#4]
<img width="468" alt="Screenshot 2024-10-26 at 12 28 22 PM" src="https://github.com/user-attachments/assets/f4ffd492-466b-4b41-a685-f265eb8d3585">
this recipe exists in farmer'sd elight

**Comment by PhantomWing** [comment]
I forgot this was a feature! I will add it in the next release! Thanks for mentioning it :)

**Comment by PhantomWing** [comment]
I added a cutting recipe for Cherry Blossom Cheesecake in the NeoForge 1.21.1 version! Releases for the other versions will follow.
