### ISSUE TITLE
Not compatible with 1.21, only 1.21.1 despite modrinth page claiming 1.21 compatibility

### ISSUE THREAD

**Issue by Ranses969** [PhantomWing/RusticDelight#7]
Modrinth page claims mod is compatible with 1.21
World cannot be ran using forge 1.21
Error Message: 

"Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
Replace mod 'Rustic Delight' (rusticdelight) 1.0.0 with any version that is compatible with:
minecraft 1.21
More details:
<html>Mod 'Rustic Delight' (rusticdelight) 1.0.0 requires any version between 1.21.1 (inclusive) and 1.22- (exclusive) of<br>'Minecraft' (minecraft), but only the wrong version is present: 1.21!</html>"

**Comment by PhantomWing** [comment]
Thanks for addressing the issue! I'm working on it right now, and will let you know when a fix is available.

**Comment by PhantomWing** [comment]
A new version is now available for download, which should be compatible with 1.21 now! Hope you enjoy the mod!
